[project]
name = "axis-wolf-backend"
version = "0.1.0"
description = "FastAPI backend for Axis Wolf online game"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.4",
    "uvicorn[standard]>=0.32.0",
    "websockets>=13.1",
    "pydantic>=2.9.2",
    "python-multipart>=0.0.12",
]
